CREATE TABLE IF NOT EXISTS nflverse.player_passing (
    player_id TEXT NOT NULL REFERENCES nflverse.players(player_id),
    name TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    completions INTEGER,
    attempts INTEGER,
    yards INTEGER,
    tds INTEGER,
    ints INTEGER,
    sacks INTEGER,
    sack_yards_lost INTEGER,
    sack_fumbles INTEGER,
    sack_fumbles_lost INTEGER,
    air_yards INTEGER,
    yac INTEGER,
    first_down INTEGER,
    epa INTEGER,
    cpoe INTEGER,
    two_pt_conv INTEGER,
    pacr INTEGER,
    PRIMARY KEY (player_id, season, week, season_type) 
);

CREATE TABLE IF NOT EXISTS nflverse.player_rushing (
    player_id TEXT REFERENCES nflverse.players(player_id),
    name TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    carries INTEGER,
    yards INTEGER,
    tds INTEGER,
    fumbles INTEGER,
    fumbles_lost INTEGER,
    first_down INTEGER,
    epa INTEGER,
    two_pt_conv INTEGER,
    PRIMARY KEY (player_id, season, week, season_type) 
);

CREATE TABLE IF NOT EXISTS nflverse.player_receiving (
    player_id TEXT REFERENCES nflverse.players(player_id),
    name TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    receptions INTEGER,
    targets INTEGER,
    yards INTEGER,
    tds INTEGER,
    fumbles INTEGER,
    fumbles_lost INTEGER,
    air_yards INTEGER,
    yac INTEGER,
    first_down INTEGER,
    epa INTEGER,
    two_pt_conv INTEGER,
    racr INTEGER,
    tar_share INTEGER,
    a_y_share INTEGER,
    wopr INTEGER,
    PRIMARY KEY (player_id, season, week, season_type) 
); 

CREATE TABLE IF NOT EXISTS nflverse.player_kicking (
    player_id TEXT REFERENCES nflverse.players(player_id),
    name TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    made INTEGER,
    att INTEGER,
    missed INTEGER,
    blocked INTEGER,
    fg_long INTEGER,
    pct INTEGER,
    made_0_19 INTEGER,
    made_20_29 INTEGER,
    made_30_39 INTEGER,
    made_40_49 INTEGER,
    made_50_59 INTEGER,
    made_60_ INTEGER,
    missed_0_19 INTEGER,
    missed_20_29 INTEGER,
    missed_30_39 INTEGER,
    missed_40_49 INTEGER,
    missed_50_59 INTEGER,
    missed_60_ INTEGER,
    made_list INTEGER[],
    missed_list INTEGER[],
    blocked_list INTEGER[],
    made_distance INTEGER,
    missed_distance INTEGER,
    blocked_distance INTEGER,
    pat_made INTEGER,
    pat_att INTEGER,
    pat_missed INTEGER,
    pat_blocked INTEGER,
    pat_pct INTEGER,
    gwfg_made INTEGER,
    gwfg_att INTEGER,
    gwfg_missed INTEGER,
    gwfg_blocked INTEGER,
    gwfg_distance INTEGER, 
    PRIMARY KEY (player_id, season, week, season_type) 
);

CREATE TABLE IF NOT EXISTS nflverse.player_st (
    player_id TEXT REFERENCES nflverse.players(player_id),
    name TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    punt_returns INTEGER,
    punt_return_yards INTEGER,
    kickoff_returns INTEGER,
    kickoff_return_yards INTEGER,
    tds INTEGER,
    PRIMARY KEY (player_id, season, week, season_type) 
);

CREATE TABLE IF NOT EXISTS nflverse.player_defense (
    player_id TEXT REFERENCES nflverse.players(player_id),
    name TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    tackles_solo INTEGER,
    tackles_with_assist INTEGER,
    tackle_assists INTEGER,
    tackles_for_loss INTEGER,
    tackles_for_loss_yards INTEGER,
    fumbles_forced INTEGER,
    sacks INTEGER,
    sack_yards INTEGER,
    qb_hits INTEGER,
    interceptions INTEGER,
    interception_yards INTEGER,
    pass_defended INTEGER,
    tds INTEGER,
    fumbles INTEGER,
    safeties INTEGER,
    PRIMARY KEY (player_id, season, week, season_type) 
);

CREATE TABLE IF NOT EXISTS nflverse.player_misc (
    player_id TEXT REFERENCES nflverse.players(player_id),
    name TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    yards INTEGER,
    fumble_recovery_own INTEGER,
    fumble_recovery_yards_own INTEGER,
    fumble_recovery_opp INTEGER,
    fumble_recovery_yards_opp INTEGER,
    fumble_recovery_tds INTEGER,
    penalties INTEGER,
    penalty_yards INTEGER, 
    PRIMARY KEY (player_id, season, week, season_type) 
);
