CREATE TABLE IF NOT EXISTS nflverse.team_offense (
    team TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    completions INTEGER,
    attempts INTEGER,
    passing_yards INTEGER,
    passing_tds INTEGER,
    passing_interceptions INTEGER,
    sacks_suffered INTEGER,
    sack_yards_lost INTEGER,
    sack_fumbles INTEGER,
    sack_fumbles_lost INTEGER,
    passing_air_yards INTEGER,
    passing_yards_after_catch INTEGER,
    passing_first_downs INTEGER,
    passing_epa NUMERIC(8,4),
    passing_2pt_conversions INTEGER,
    carries INTEGER,
    rushing_yards INTEGER,
    rushing_tds INTEGER,
    rushing_fumbles INTEGER,
    rushing_fumbles_lost INTEGER,
    rushing_first_downs INTEGER,
    rushing_epa NUMERIC(8,4),
    rushing_2pt_conversions INTEGER,
    receptions INTEGER,
    targets INTEGER,
    receiving_yards INTEGER,
    receiving_tds INTEGER,
    receiving_fumbles INTEGER,
    receiving_fumbles_lost INTEGER,
    receiving_air_yards INTEGER,
    receiving_yards_after_catch INTEGER,
    receiving_first_downs INTEGER,
    receiving_epa INTEGER,
    receiving_2pt_conversions INTEGER,
    PRIMARY KEY (team, season, week, season_type)
);

CREATE TABLE IF NOT EXISTS nflverse.team_defense (
    team TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    def_tackles_solo INTEGER,
    def_tackles_with_assist INTEGER,
    def_tackle_assists INTEGER,
    def_tackles_for_loss INTEGER,
    def_tackles_for_loss_yards INTEGER,
    def_fumbles_forced INTEGER,
    def_sacks INTEGER,
    def_sack_yards INTEGER,
    def_qb_hits INTEGER,
    def_interceptions INTEGER,
    def_interception_yards INTEGER,
    def_pass_defended INTEGER,
    def_tds INTEGER,
    def_fumbles INTEGER,
    def_safeties INTEGER,
    PRIMARY KEY (team, season, week, season_type)
);

CREATE TABLE IF NOT EXISTS nflverse.team_kicking (
    team TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    fg_made INTEGER,
    made INTEGER,
    att INTEGER,
    missed INTEGER,
    blocked INTEGER,
    fg_long INTEGER,
    pct NUMERIC(5,4),
    made_0_19 INTEGER,
    made_20_29 INTEGER,
    made_30_39 INTEGER,
    made_40_49 INTEGER,
    made_50_59 INTEGER,
    made_60_ INTEGER,
    missed_0_19 INTEGER,
    missed_20_29 INTEGER,
    missed_30_39 INTEGER,
    missed_40_49 INTEGER,
    missed_50_59 INTEGER,
    missed_60_ INTEGER,
    made_list INTEGER[],
    missed_list INTEGER[],
    blocked_list INTEGER[],
    made_distance INTEGER,
    missed_distance INTEGER,
    blocked_distance INTEGER,
    pat_made INTEGER,
    pat_att INTEGER,
    pat_missed INTEGER,
    pat_blocked INTEGER,
    pat_pct NUMERIC(5,4),
    gwfg_made INTEGER,
    gwfg_att INTEGER,
    gwfg_missed INTEGER,
    gwfg_blocked INTEGER,
    gwfg_distance INTEGER,g_att INTEGER,
    PRIMARY KEY (team, season, week, season_type)
);

CREATE TABLE IF NOT EXISTS nflverse.team_misc (
    team TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    yards INTEGER,
    fumble_recovery_own INTEGER,
    fumble_recovery_yards_own INTEGER,
    fumble_recovery_opp INTEGER,
    fumble_recovery_yards_opp INTEGER,
    fumble_recovery_tds INTEGER,
    penalties INTEGER,
    penalty_yards INTEGER, 
    PRIMARY KEY (team, season, week, season_type)
);

CREATE TABLE IF NOT EXISTS nflverse.team_special_teams (
    team TEXT NOT NULL,
    season INTEGER,
    week INTEGER,
    season_type TEXT,
    punt_returns INTEGER,
    punt_return_yards INTEGER,
    kickoff_returns INTEGER,
    kickoff_return_yards INTEGER,
    tds INTEGER,
    PRIMARY KEY (team, season, week, season_type)
);
